template: 'facelessuser:master-labels:labels.yml:master'

# Wildcard labels

brace_expansion: true
extended_glob: true

rules:
  - labels: [infrastructure]
    patterns: ['*|-@(*.md|*.py|*.sublime-@(keymap|menu|settings|commands))', '@(requirements|.github)/**']

  - labels: [source]
    patterns: ['**/*.py|-tests']

  - labels: [docs]
    patterns: ['**/*.md|docs/**']

  - labels: [tests]
    patterns: ['tests/**']

  - labels: [plugins]
    patterns: ['bh_modules/**|bh_plugin.py']

  - labels: [swapping]
    patterns: ['**/*swapping*']

  - labels: [wrapping]
    patterns: ['**/*wrapping*']

  - labels: [core]
    patterns: ['**/*core*']

  - labels: [logging]
    patterns: ['bh_logging.py']

  - labels: [popups]
    patterns: ['bh_popup.py']

  - labels: [regions]
    patterns: ['bh_regions.py']

  - labels: [remove]
    patterns: ['bh_remove.py']

  - labels: [rules]
    patterns: ['bh_rules.py']

  - labels: [search]
    patterns: ['bh_search.py']

  - labels: [tags]
    patterns: ['**/bh_modules/tag@(s|attrselect|nameselect).py|bh_tag.sublime-settings']

  - labels: [settings]
    patterns: ['*.sublime-@(keymap|menu|settings|commands)']

  - labels: [icons]
    patterns: ['**/icons/*']

# Label management

labels:
- name: plugins
  color: subcategory
  description: Related to plugins.

- name: swapping
  color: subcategory
  description: Related to the swapping library.

- name: wrapping
  color: subcategory
  description: Related to the wrapping library.

- name: core
  color: subcategory
  description: Related to the core code.

- name: logging
  color: subcategory
  description: Related to logging

- name: popups
  color: subcategory
  description: Related to popups

- name: regions
  color: subcategory
  description: Related to regions.

- name: remove
  color: subcategory
  description: Related to bracket removal.

- name: rules
  color: subcategory
  description: Related to bracket rules.

- name: search
  color: subcategory
  description: Related to search.

- name: tags
  color: subcategory
  description: Related to tag handling.

- name: settings
  color: subcategory
  description: Related to Sublime settings files.

- name: icons
  color: subcategory
  description: Bracket icons.
